/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedChannelsRouteRouteImport } from './routes/_authenticated/channels/route'
import { Route as AuthenticatedChannelsGuildIdRouteRouteImport } from './routes/_authenticated/channels/$guildId/route'
import { Route as AuthenticatedChannelsGuildIdChannelIdRouteImport } from './routes/_authenticated/channels/$guildId/$channelId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChannelsRouteRoute =
  AuthenticatedChannelsRouteRouteImport.update({
    id: '/_authenticated/channels',
    path: '/channels',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChannelsGuildIdRouteRoute =
  AuthenticatedChannelsGuildIdRouteRouteImport.update({
    id: '/$guildId',
    path: '/$guildId',
    getParentRoute: () => AuthenticatedChannelsRouteRoute,
  } as any)
const AuthenticatedChannelsGuildIdChannelIdRoute =
  AuthenticatedChannelsGuildIdChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AuthenticatedChannelsGuildIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/channels': typeof AuthenticatedChannelsRouteRouteWithChildren
  '/channels/$guildId': typeof AuthenticatedChannelsGuildIdRouteRouteWithChildren
  '/channels/$guildId/$channelId': typeof AuthenticatedChannelsGuildIdChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/channels': typeof AuthenticatedChannelsRouteRouteWithChildren
  '/channels/$guildId': typeof AuthenticatedChannelsGuildIdRouteRouteWithChildren
  '/channels/$guildId/$channelId': typeof AuthenticatedChannelsGuildIdChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRouteRouteWithChildren
  '/_authenticated/channels/$guildId': typeof AuthenticatedChannelsGuildIdRouteRouteWithChildren
  '/_authenticated/channels/$guildId/$channelId': typeof AuthenticatedChannelsGuildIdChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/channels'
    | '/channels/$guildId'
    | '/channels/$guildId/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/channels'
    | '/channels/$guildId'
    | '/channels/$guildId/$channelId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/_authenticated/channels'
    | '/_authenticated/channels/$guildId'
    | '/_authenticated/channels/$guildId/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthenticatedChannelsRouteRoute: typeof AuthenticatedChannelsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/channels/$guildId': {
      id: '/_authenticated/channels/$guildId'
      path: '/$guildId'
      fullPath: '/channels/$guildId'
      preLoaderRoute: typeof AuthenticatedChannelsGuildIdRouteRouteImport
      parentRoute: typeof AuthenticatedChannelsRouteRoute
    }
    '/_authenticated/channels/$guildId/$channelId': {
      id: '/_authenticated/channels/$guildId/$channelId'
      path: '/$channelId'
      fullPath: '/channels/$guildId/$channelId'
      preLoaderRoute: typeof AuthenticatedChannelsGuildIdChannelIdRouteImport
      parentRoute: typeof AuthenticatedChannelsGuildIdRouteRoute
    }
  }
}

interface AuthenticatedChannelsGuildIdRouteRouteChildren {
  AuthenticatedChannelsGuildIdChannelIdRoute: typeof AuthenticatedChannelsGuildIdChannelIdRoute
}

const AuthenticatedChannelsGuildIdRouteRouteChildren: AuthenticatedChannelsGuildIdRouteRouteChildren =
  {
    AuthenticatedChannelsGuildIdChannelIdRoute:
      AuthenticatedChannelsGuildIdChannelIdRoute,
  }

const AuthenticatedChannelsGuildIdRouteRouteWithChildren =
  AuthenticatedChannelsGuildIdRouteRoute._addFileChildren(
    AuthenticatedChannelsGuildIdRouteRouteChildren,
  )

interface AuthenticatedChannelsRouteRouteChildren {
  AuthenticatedChannelsGuildIdRouteRoute: typeof AuthenticatedChannelsGuildIdRouteRouteWithChildren
}

const AuthenticatedChannelsRouteRouteChildren: AuthenticatedChannelsRouteRouteChildren =
  {
    AuthenticatedChannelsGuildIdRouteRoute:
      AuthenticatedChannelsGuildIdRouteRouteWithChildren,
  }

const AuthenticatedChannelsRouteRouteWithChildren =
  AuthenticatedChannelsRouteRoute._addFileChildren(
    AuthenticatedChannelsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthenticatedChannelsRouteRoute: AuthenticatedChannelsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
